"""Align public schema metadata with SQLAlchemy models.

Revision ID: 509e32610a76
Revises: e2f5b7719c31
Create Date: 2026-06-10 18:24:55.020082

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "509e32610a76"
down_revision: str | Sequence[str] | None = "e2f5b7719c31"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_ai_analyses_candidate_id'), table_name='ai_analyses')
    op.drop_index(op.f('idx_ai_analyses_status'), table_name='ai_analyses')
    op.create_index(
        op.f("ix_public_ai_analyses_candidate_id"),
        "ai_analyses",
        ["candidate_id"],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_ai_analyses_status"),
        "ai_analyses",
        ["status"],
        unique=False,
        schema="public",
    )
    op.drop_constraint(op.f('ai_analyses_candidate_id_fkey'), 'ai_analyses', type_='foreignkey')
    op.drop_constraint(op.f('ai_analyses_job_posting_id_fkey'), 'ai_analyses', type_='foreignkey')
    op.create_foreign_key(
        None,
        "ai_analyses",
        "job_postings",
        ["job_posting_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "ai_analyses",
        "candidate_profiles",
        ["candidate_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
        ondelete="CASCADE",
    )
    op.alter_column(
        'billing_prices',
        'created_at',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text('now()'),
    )
    op.alter_column(
        'billing_prices',
        'updated_at',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text('now()'),
    )
    op.drop_index(op.f('ix_billing_prices_plan'), table_name='billing_prices')
    op.create_index(
        op.f('ix_public_billing_prices_plan'),
        'billing_prices',
        ['plan'],
        unique=False,
        schema='public',
    )
    op.drop_constraint(
        op.f('candidate_embeddings_candidate_id_fkey'),
        'candidate_embeddings',
        type_='foreignkey',
    )
    op.create_foreign_key(
        None,
        "candidate_embeddings",
        "candidate_profiles",
        ["candidate_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f('candidate_profiles_user_id_fkey'),
        'candidate_profiles',
        type_='foreignkey',
    )
    op.create_foreign_key(
        None,
        "candidate_profiles",
        "users",
        ["user_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f('job_embeddings_job_posting_id_fkey'),
        'job_embeddings',
        type_='foreignkey',
    )
    op.create_foreign_key(
        None,
        "job_embeddings",
        "job_postings",
        ["job_posting_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f('password_reset_tokens_candidate_id_fkey'),
        'password_reset_tokens',
        type_='foreignkey',
    )
    op.create_foreign_key(
        None,
        "password_reset_tokens",
        "users",
        ["candidate_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
        ondelete="CASCADE",
    )
    op.drop_constraint(op.f('refresh_tokens_user_id_fkey'), 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(
        None,
        "refresh_tokens",
        "users",
        ["user_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
        ondelete="CASCADE",
    )
    op.create_index(
        op.f("ix_public_search_agents_candidate_id"),
        "search_agents",
        ["candidate_id"],
        unique=False,
        schema="public",
    )
    op.drop_constraint(op.f('search_agents_candidate_id_fkey'), 'search_agents', type_='foreignkey')
    op.create_foreign_key(
        None,
        "search_agents",
        "users",
        ["candidate_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
        ondelete="CASCADE",
    )
    op.drop_constraint(op.f('subscriptions_user_id_fkey'), 'subscriptions', type_='foreignkey')
    op.drop_constraint(
        op.f('subscriptions_billing_price_id_fkey'),
        'subscriptions',
        type_='foreignkey',
    )
    op.create_foreign_key(
        None,
        "subscriptions",
        "billing_prices",
        ["billing_price_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        None,
        "subscriptions",
        "users",
        ["user_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "subscriptions_billing_price_id_fkey",
        "subscriptions",
        schema="public",
        type_="foreignkey",
    )
    op.drop_constraint(
        "subscriptions_user_id_fkey",
        "subscriptions",
        schema="public",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f('subscriptions_billing_price_id_fkey'),
        'subscriptions',
        'billing_prices',
        ['billing_price_id'],
        ['id'],
        ondelete='SET NULL',
    )
    op.create_foreign_key(
        op.f('subscriptions_user_id_fkey'),
        'subscriptions',
        'users',
        ['user_id'],
        ['id'],
        ondelete='CASCADE',
    )
    op.drop_constraint(
        "search_agents_candidate_id_fkey",
        "search_agents",
        schema="public",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f('search_agents_candidate_id_fkey'),
        'search_agents',
        'users',
        ['candidate_id'],
        ['id'],
        ondelete='CASCADE',
    )
    op.drop_index(
        op.f('ix_public_search_agents_candidate_id'),
        table_name='search_agents',
        schema='public',
    )
    op.drop_constraint(
        "refresh_tokens_user_id_fkey",
        "refresh_tokens",
        schema="public",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f('refresh_tokens_user_id_fkey'),
        'refresh_tokens',
        'users',
        ['user_id'],
        ['id'],
        ondelete='CASCADE',
    )
    op.drop_constraint(
        "password_reset_tokens_candidate_id_fkey",
        "password_reset_tokens",
        schema="public",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f('password_reset_tokens_candidate_id_fkey'),
        'password_reset_tokens',
        'users',
        ['candidate_id'],
        ['id'],
        ondelete='CASCADE',
    )
    op.drop_constraint(
        "job_embeddings_job_posting_id_fkey",
        "job_embeddings",
        schema="public",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f('job_embeddings_job_posting_id_fkey'),
        'job_embeddings',
        'job_postings',
        ['job_posting_id'],
        ['id'],
        ondelete='CASCADE',
    )
    op.drop_constraint(
        "candidate_profiles_user_id_fkey",
        "candidate_profiles",
        schema="public",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f('candidate_profiles_user_id_fkey'),
        'candidate_profiles',
        'users',
        ['user_id'],
        ['id'],
        ondelete='CASCADE',
    )
    op.drop_constraint(
        "candidate_embeddings_candidate_id_fkey",
        "candidate_embeddings",
        schema="public",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f('candidate_embeddings_candidate_id_fkey'),
        'candidate_embeddings',
        'candidate_profiles',
        ['candidate_id'],
        ['id'],
        ondelete='CASCADE',
    )
    op.drop_index(
        op.f('ix_public_billing_prices_plan'),
        table_name='billing_prices',
        schema='public',
    )
    op.create_index(op.f('ix_billing_prices_plan'), 'billing_prices', ['plan'], unique=False)
    op.alter_column(
        'billing_prices',
        'updated_at',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text('now()'),
    )
    op.alter_column(
        'billing_prices',
        'created_at',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text('now()'),
    )
    op.drop_constraint(
        "ai_analyses_job_posting_id_fkey",
        "ai_analyses",
        schema="public",
        type_="foreignkey",
    )
    op.drop_constraint(
        "ai_analyses_candidate_id_fkey",
        "ai_analyses",
        schema="public",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f('ai_analyses_job_posting_id_fkey'),
        'ai_analyses',
        'job_postings',
        ['job_posting_id'],
        ['id'],
        ondelete='CASCADE',
    )
    op.create_foreign_key(
        op.f('ai_analyses_candidate_id_fkey'),
        'ai_analyses',
        'candidate_profiles',
        ['candidate_id'],
        ['id'],
        ondelete='CASCADE',
    )
    op.drop_index(
        op.f('ix_public_ai_analyses_status'),
        table_name='ai_analyses',
        schema='public',
    )
    op.drop_index(
        op.f('ix_public_ai_analyses_candidate_id'),
        table_name='ai_analyses',
        schema='public',
    )
    op.create_index(op.f('idx_ai_analyses_status'), 'ai_analyses', ['status'], unique=False)
    op.create_index(
        op.f('idx_ai_analyses_candidate_id'),
        'ai_analyses',
        ['candidate_id'],
        unique=False,
    )
    # ### end Alembic commands ###
