"""add search_agents table

Revision ID: 568ce812c1e5
Revises: 9cf37244a7c6
Create Date: 2026-05-06 20:43:58.002623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '568ce812c1e5'
down_revision: Union[str, Sequence[str], None] = '9cf37244a7c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('candidate_profiles_user_id_fkey'), 'candidate_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'candidate_profiles', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('search_agents_candidate_id_fkey'), 'search_agents', type_='foreignkey')
    op.create_foreign_key(None, 'search_agents', 'users', ['candidate_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('subscriptions_user_id_fkey'), 'subscriptions', type_='foreignkey')
    op.drop_constraint(op.f('subscriptions_billing_price_id_fkey'), 'subscriptions', type_='foreignkey')
    op.create_foreign_key(None, 'subscriptions', 'billing_prices', ['billing_price_id'], ['id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.create_foreign_key(None, 'subscriptions', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscriptions', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'subscriptions', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('subscriptions_billing_price_id_fkey'), 'subscriptions', 'billing_prices', ['billing_price_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('subscriptions_user_id_fkey'), 'subscriptions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'search_agents', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('search_agents_candidate_id_fkey'), 'search_agents', 'users', ['candidate_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'candidate_profiles', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('candidate_profiles_user_id_fkey'), 'candidate_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
