"""add_linkedin_id_and_avatar_url_to_users

Revision ID: cf91135dcbb2
Revises: d6c0ac4f6d35
Create Date: 2026-05-06 16:44:01.851689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf91135dcbb2'
down_revision: Union[str, Sequence[str], None] = 'd6c0ac4f6d35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('subscriptions_billing_price_id_fkey'), 'subscriptions', type_='foreignkey')
    op.drop_constraint(op.f('subscriptions_user_id_fkey'), 'subscriptions', type_='foreignkey')
    op.create_foreign_key(None, 'subscriptions', 'billing_prices', ['billing_price_id'], ['id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.create_foreign_key(None, 'subscriptions', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.add_column('users', sa.Column('linkedin_id', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(length=512), nullable=True))
    op.create_index(op.f('ix_public_users_linkedin_id'), 'users', ['linkedin_id'], unique=True, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_users_linkedin_id'), table_name='users', schema='public')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'linkedin_id')
    op.drop_constraint(None, 'subscriptions', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'subscriptions', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('subscriptions_user_id_fkey'), 'subscriptions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('subscriptions_billing_price_id_fkey'), 'subscriptions', 'billing_prices', ['billing_price_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
