"""Stripe subscription

Revision ID: 8f0c147e01db
Revises: 202512231200abcdef123456
Create Date: 2026-03-25 15:45:21.969168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f0c147e01db'
down_revision: Union[str, Sequence[str], None] = '202512231200abcdef123456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(), nullable=True),
    sa.Column('plan', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['public.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_subscriptions_stripe_customer_id'), 'subscriptions', ['stripe_customer_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_subscriptions_stripe_subscription_id'), 'subscriptions', ['stripe_subscription_id'], unique=True, schema='public')
    op.create_index(op.f('ix_public_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=True, schema='public')
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('scheduled_purge_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f('ix_public_users_email'), table_name='users')
    op.create_index(op.f('ix_public_users_deleted_at'), 'users', ['deleted_at'], unique=False, schema='public')
    op.create_index(op.f('ix_public_users_scheduled_purge_at'), 'users', ['scheduled_purge_at'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_users_scheduled_purge_at'), table_name='users', schema='public')
    op.drop_index(op.f('ix_public_users_deleted_at'), table_name='users', schema='public')
    op.create_index(op.f('ix_public_users_email'), 'users', ['email'], unique=True)
    op.drop_column('users', 'scheduled_purge_at')
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'is_deleted')
    op.drop_index(op.f('ix_public_subscriptions_user_id'), table_name='subscriptions', schema='public')
    op.drop_index(op.f('ix_public_subscriptions_stripe_subscription_id'), table_name='subscriptions', schema='public')
    op.drop_index(op.f('ix_public_subscriptions_stripe_customer_id'), table_name='subscriptions', schema='public')
    op.drop_table('subscriptions', schema='public')
    # ### end Alembic commands ###
